name: 编译并发布

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: 构建工程
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: true
      - name: 发布Maven仓库
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_args: '-DskipTests'
          maven_profile: 'release'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}
          server_id: OSSRH